---
- hosts: all
  become: true
  become_method: sudo
  become_user: ansadm

  tasks:
    - name: installing apache
      yum: name=httpd state=installed

    - name: checking the apache installed or not
      shell: "sudo yum list httpd"

    - name: starting my apache server 
      service: name=httpd state=started
