# copywarfile.yml
---
- hosts: all 
  become: true
  tasks: 
    - name: copy jar/war onto tomcat servers
      copy:
          src: ${WORKSPACE}/gameoflife.war
          dest: /usr/share/tomcat/webapps
