# copywarfile.yml
---
- hosts: all 
  become: true
  tasks: 
    - name: copy jar/war onto tomcat servers
      copy:
          src: /var/lib/jenkins/workspace/Ansible_S3Artifact_Playbooks-Deploy-tomcat/gameoflife.war
          dest: /usr/share/tomcat/webapps
