---
- hosts: localhost

  tasks:
    - name: this is just launching ec2
      ec2:
        key_name: KSClass-v11
        instance_type: t2.micro
        image: ami-065d4c51ae9e6312d
        wait: yes
        group: MySG-Group-Master
        count: 1
        vpc_subnet_id: subnet-09f1637bde6401b61
        assign_public_ip: yes
        region: us-west-2

      register: ec2
