---
- hosts: localhost
  vars:
    ec2_instance_ids : i-062854b4cc94295c2


  tasks:
     - name: Terminate instances that were previously launched
       ec2:
         state: 'absent'
         region: us-west-2
         wait: true
         instance_ids: '{{ ec2_instance_ids }}'
